controllers:
    resource: ../src/Shared/Infrastructure/Controller/
    type: attribute

gesdinet_jwt_refresh_token:
    path: /api/auth/token/refresh

api_login_check:
    path: /api/auth/token/login

users:
    resource: ../src/User/Infrastructure/Controller/
    type: attribute

band:
    resource: ../src/Band/Infrastructure/Controller/
    type: attribute