App\Band\Domain\Model\Song:
    type: entity
    table: song
    repositoryClass: App\Band\Infrastructure\Domain\Repository\DoctrineSongRepository
    id:
        id:
            type: integer
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
        time:
            type: time_immutable
            nullable: false
    manyToOne:
        album:
            targetEntity: App\Band\Domain\Model\Album
            inversedBy: albums
            joinColumn:
                name: album_id
                referencedColumnName: id
                nullable: false
